# Generated by Django 2.0.6 on 2018-06-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180614_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='origin_url',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
