# Generated by Django 2.0.6 on 2018-06-15 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180614_1520'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-saved_at']},
        ),
    ]
